[package]
name = "car"
version = "0.0.1"
description = "A library to encode and handle CAR files in Motoko"
repository = "https://github.com/edjcase/motoko_car"
keywords = [ "car", "ipld", "atproto", "archive", "ipfs" ]
license = "MIT"

[dependencies]
base = "0.14.14"
new-base = "0.4.0"
cid = "0.1.6"
dag-cbor = "1.0.4"
multiformats = "0.3.1"

[dev-dependencies]
test = "2.1.1"

[toolchain]
moc = "0.14.14"
